//USER TYPES
export const USER_LOGIN = "USER_LOGIN"
export const USER_REGISTER = "USER_REGISTER"

//CONTACTS TYPES
export const CREATE_CONTACT = "CREATE_CONTACT"
export const GET_ALL_CONTACTS = "GET_ALL_CONTACTS"
export const DELETE_CONTACT = "DELETE_CONTACT"
export const CHANGE_CONTACT = "CHANGE_CONTACT"
